### ISSUE TITLE
CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by mocha1908** [zhuang2002/PowerPaint#102]
0%|                                                                                                                                               | 0/45 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/home/cwj/Computer_Vision/Image_Quality_Assessment/Image_Score/negative_outpaint.py", line 486, in <module>
    inpaint_result, gallery = controller.infer(input_image,
  File "/home/cwj/Computer_Vision/Image_Quality_Assessment/Image_Score/negative_outpaint.py", line 407, in infer
    return self.predict(
  File "/home/cwj/Computer_Vision/Image_Quality_Assessment/Image_Score/negative_outpaint.py", line 328, in predict
    result = self.pipe(
  File "/home/anaconda3/envs/powerpaint/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/cwj/Computer_Vision/Image_Quality_Assessment/Image_Score/powerpaint/pipelines/pipeline_PowerPaint_Brushnet_CA.py", line 1427, in __call__
    down_block_res_samples, mid_block_res_sample, up_block_res_samples = self.brushnet(
  File "/home/anaconda3/envs/powerpaint/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/anaconda3/envs/powerpaint/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/anaconda3/envs/powerpaint/lib/python3.9/site-packages/accelerate/hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/cwj/Computer_Vision/Image_Quality_Assessment/Image_Score/powerpaint/models/BrushNet_CA.py", line 829, in forward
    sample, res_samples = downsample_block(
  File "/home/anaconda3/envs/powerpaint/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/anaconda3/envs/powerpaint/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/cwj/Computer_Vision/Image_Quality_Assessment/Image_Score/powerpaint/models/unet_2d_blocks.py", line 1374, in forward
    hidden_states = resnet(hidden_states, temb, scale=lora_scale)
  File "/home/anaconda3/envs/powerpaint/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/anaconda3/envs/powerpaint/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/anaconda3/envs/powerpaint/lib/python3.9/site-packages/diffusers/models/resnet.py", line 332, in forward
    hidden_states = self.norm1(hidden_states)
  File "/home/anaconda3/envs/powerpaint/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/anaconda3/envs/powerpaint/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/anaconda3/envs/powerpaint/lib/python3.9/site-packages/torch/nn/modules/normalization.py", line 287, in forward
    return F.group_norm(
  File "/home/anaconda3/envs/powerpaint/lib/python3.9/site-packages/torch/nn/functional.py", line 2588, in group_norm
    return torch.group_norm(input, num_groups, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Hello Author,I'm encountering an issue when running the Image Outpainting method. Despite adjusting the image size to 224x224, the problem persists. How should I resolve this?

**Comment by zengyh1900** [comment]
hi @mocha1908 
Is it normal for other types of inpainting tasks? If so, then outpainting often encounters CUDA memory issues. You can check your target output resolution.

**Comment by mocha1908** [comment]
> 你好@mocha1908 对于其他类型的修复任务来说，这是否正常？如果是，那么修复经常会遇到 CUDA 内存问题。您可以检查目标输出分辨率。

你好，我是调用ppt-v2-1这个里面的模型，然后我想把整个代码都放在指定的显卡上，但是我在主代码将模型放在指定显卡上，后面导入外部模型开始运行后还是在默认显卡上，我该如何修改代码？

**Comment by Mooniui** [comment]
Hi, I'm getting the same error, how to handle these:

RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
