### ISSUE TITLE
ERROR:改变了分支还是遇到了下面的错误  OSError: runwayml/stable-diffusion-v1-5 does not appear to have a file named config.json.

### ISSUE THREAD

**Issue by HarlayZhang** [zhuang2002/PowerPaint#135]
Traceback (most recent call last):
  File "/home/uxxxxxxxxx/PowerPaint/app.py", line 560, in <module>
    controller = PowerPaintController(weight_dtype, args.checkpoint_dir, args.local_files_only, args.version)
  File "/home/uxxxxxxxxx/PowerPaint/app.py", line 141, in __init__
    unet = UNet2DConditionModel.from_pretrained(
  File "/home/uxxxxxxxxx/.local/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/uxxxxxxxxx/.conda/envs/ppt/lib/python3.9/site-packages/diffusers/models/modeling_utils.py", line 567, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
  File "/home/uxxxxxxxxx/.local/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/uxxxxxxxxx/.conda/envs/ppt/lib/python3.9/site-packages/diffusers/configuration_utils.py", line 406, in load_config
    raise EnvironmentError(
OSError: runwayml/stable-diffusion-v1-5 does not appear to have a file named config.json.

**Comment by lvhongyi1** [comment]
请问解决了吗

**Comment by HarlayZhang** [comment]
> 请问解决了吗

没有

**Comment by fushi219** [comment]
一样的问题

**Comment by chaledelta** [comment]
一样的问题

**Comment by Higasa-Yumetaka** [comment]
貌似runwayml/stable-diffusion-v1-5已经从huggingface_hub删除了，详见https://github.com/huggingface/optimum-habana/issues/1305
可以试一下改为这个https://huggingface.co/stable-diffusion-v1-5/stable-diffusion-v1-5

**Comment by Asyou-GD** [comment]
没用，显示键值权重对应不上

**Comment by Techhooli** [comment]
我去。。。搞了半天，这个项目根本就无法运行起来了，碰到相同问题。。。

**Comment by zhuang2002** [comment]
> 我去。。。搞了半天，这个项目根本就无法运行起来了，碰到相同问题。。。

感谢反馈！
目前 runwayml/stable-diffusion-v1-5 仓库已经被 Runway 删除，导致 config.json 等关键文件无法访问，从而触发了上述报错。
为了解决这个问题，请将模型路径替换为：
stable-diffusion-v1-5/stable-diffusion-v1-5
该仓库内容与原始 SD-1.5 匹配，目前仍然可用。这样修改后即可正常运行。

**Comment by Techhooli** [comment]
同样不行，因为stable-diffusion-v1-5/stable-diffusion-v1-5依然没有config.json，我不清楚这个文件是啥。。能自己补充吗？

> > 我去。。。搞了半天，这个项目根本就无法运行起来了，碰到相同问题。。。
> 
> 感谢反馈！ 目前 runwayml/stable-diffusion-v1-5 仓库已经被 Runway 删除，导致 config.json 等关键文件无法访问，从而触发了上述报错。 为了解决这个问题，请将模型路径替换为： stable-diffusion-v1-5/stable-diffusion-v1-5 该仓库内容与原始 SD-1.5 匹配，目前仍然可用。这样修改后即可正常运行。

**Comment by Techhooli** [comment]
<img width="668" height="312" alt="Image" src="https://github.com/user-attachments/assets/52a192e0-74a5-4886-aa5b-dfc25114364f" />如图所示修改，请问是这样吗？提示如下：

<img width="1180" height="46" alt="Image" src="https://github.com/user-attachments/assets/fbd71916-cc2e-45eb-bcbf-ad8013fe305b" />

**Comment by Asyou-GD** [comment]
> <img alt="图像" width="668" height="312" src="https://private-user-images.githubusercontent.com/23013071/486653522-52a192e0-74a5-4886-aa5b-dfc25114364f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTczMTc0MDUsIm5iZiI6MTc1NzMxNzEwNSwicGF0aCI6Ii8yMzAxMzA3MS80ODY2NTM1MjItNTJhMTkyZTAtNzRhNS00ODg2LWFhNWItZGZjMjUxMTQzNjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTA4VDA3MzgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjMmZmZWUwNThiNThiZDI2ZDY3MWQ5YTI4MjU3YTUwOTMyMDFmODQ3OWM5MGU3ZWZkZWM3MjRjOTNkMzZhM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8a79qz7o6_IoWua0THIVrFG1-7ZxxoTkaMhFMepF8RM">如图所示修改，请问是这样吗？提示如下：
> 
> <img alt="图像" width="1180" height="46" src="https://private-user-images.githubusercontent.com/23013071/486654170-fbd71916-cc2e-45eb-bcbf-ad8013fe305b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTczMTc0MDUsIm5iZiI6MTc1NzMxNzEwNSwicGF0aCI6Ii8yMzAxMzA3MS80ODY2NTQxNzAtZmJkNzE5MTYtY2MyZS00NWViLWJjYmYtYWQ4MDEzZmUzMDViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTA4VDA3MzgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmMDNlZjhmYjgxYzU4MjY5NTRhZjY0NjRjZmM5YmMxODUyY2Y0OThiMjc4MzlhYjZjNDg1Y2NhOTA5MGU4NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Tz7kfg520teWdJWXXpIWgKhvGKrZ5NBHBgagcEsmYxc">

模型只需要下载unet ， text_encoder 下载到本地加载试试
