### ISSUE TITLE
FileNotFoundError: No such file or directory: "./models/unet/diffusion_pytorch_model.safetensors"

### ISSUE THREAD

**Issue by JohanHuynh0130** [zhuang2002/PowerPaint#16]
Thanks for the work, just wondering whether huggingface accidentally deleted your files as this error happened when I tried to run Gradio:
Traceback (most recent call last):
  File "E:\mmagic\projects\powerpaint\gradio_PowerPaint.py", line 36, in <module>
    load_model(pipe.unet, './models/unet/diffusion_pytorch_model.safetensors')
  File "C:\Users\master\miniconda3\envs\PowerPaint\lib\site-packages\safetensors\torch.py", line 197, in load_model
    state_dict = load_file(filename)
  File "C:\Users\master\miniconda3\envs\PowerPaint\lib\site-packages\safetensors\torch.py", line 308, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
FileNotFoundError: No such file or directory: "./models/unet/diffusion_pytorch_model.safetensors"

**Comment by JohanHuynh0130** [comment]
Fixed! Just need to change the gradio, i think just the typo
