### ISSUE TITLE
Not able to set up app.py

### ISSUE THREAD

**Issue by kevnantony** [zhuang2002/PowerPaint#89]
Hi Guys, thank you developing this awesome project. When I'm trying to run app.py I am getting the following error:

```
Traceback (most recent call last):
  File "/home/ubuntu/PowerPaint/app.py", line 560, in <module>
    controller = PowerPaintController(weight_dtype, args.checkpoint_dir, args.local_files_only, args.version)
  File "/home/ubuntu/PowerPaint/app.py", line 111, in __init__
    load_model(self.pipe.unet, os.path.join(checkpoint_dir, "unet/unet.safetensors"))
  File "/home/ubuntu/PowerPaint/ppt/lib/python3.10/site-packages/safetensors/torch.py", line 202, in load_model
    state_dict = load_file(filename, device=device)
  File "/home/ubuntu/PowerPaint/ppt/lib/python3.10/site-packages/safetensors/torch.py", line 313, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
FileNotFoundError: No such file or directory: "./checkpoints/ppt-v1/unet/unet.safetensors"

```
I am a newbie. Could someone guide me how to fix this?

**Comment by zengyh1900** [comment]
Hi @kevnantony 
thanks for your interest. According to the error message, you need to first download related model weights to the specified path.

**Comment by kevnantony** [comment]
Much appreciated, I was able to set it up.
